### PR TITLE
Adding some improvements

### PR DESCRIPTION
**Pull request by marcelaraujo**
Adding some improvements.

Trim at classes
Indent at some source codes

### CODE REVIEW

**Comment by marcelaraujo** [comment]
Do you have some explanation to tell me the reason for this? It's an equal checking for me!

**Comment by YDyachenko** [comment]
@marcelaraujo
Because there is no div wrapper in official docs. Check "Validation states" on http://twitter.github.com/bootstrap/base-css.html#forms

**Comment by marcelaraujo** [comment]
You're right @Nice2MeatU but I can't understand the reason to change the `php !is_null($element)` for `php null !== $element`.

**Comment by YDyachenko** [comment]
@marcelaraujo oh, my fault :) posted to another tab.
it's answer for https://github.com/Emagister/zend-form-decorators-bootstrap/commit/b64069be89bd9187aa907338815f61d1fb8578ed#commitcomment-2367841

**Comment by marcelaraujo** [comment]
No problems @Nice2MeatU ;)

**Comment by theUniC** [comment]
It's just because I think that the identity operator in this case It's more meaningful and slightly more faster than a `is_null` call.

**Comment by marcelaraujo** [comment]
Ok. I do

**Pull request closed without merging**
