### PR TITLE
Some bugs fixed (helper FormUneditableTextfield and buttons)

### PR DESCRIPTION
**Pull request by leandroasp**
Correcting helper FormUneditableTextfield and fix bug in the class attribute of the buttons.

### CODE REVIEW

**Comment by theUniC** [comment]
Hi Leandro,

Thanks for the PR. I see the bug on the FormUneditableTextfield, but can you explain a bit more the bug of the class of the buttons?

Thanks!
Christian.

**Comment by leandroasp** [comment]
When I add a new class to a button, he was removing the 'btn' class and leaving only those that I added:

``` php
<?php

$this->addElement('button', 'delete', array(
    'label'       => 'Delete',
    'type'        => 'button',
    'buttonType'  => 'danger',
    'icon'        => 'trash',
    'whiteIcon'   => true,
    'class'       => 'fn-delete'
));
```

Is showing like this:

<button name="delete" id="delete" type="button" value="&lt;i class=&quot;icon-trash&quot;&gt;&lt;/i&gt;
Delete" class="fn-delete"><i class="icon-trash"></i> Delete</button>

The PR fix it.

**Comment by leandroasp** [comment]
Is showing like this:

&lt;button name="delete" id="delete" type="button" value="&lt;i class=&quot;icon-trash icon-white&quot;&gt;&lt;/i&gt;
Delete" class="fn-delete">&lt;i class="icon-trash icon-white">&lt;/i> Delete&lt;/button>

**Comment by theUniC** [comment]
Uhmm, I see. To set the `class` attribute via the `class` option is overriding the buttons classes.

OK! Thanks for the fixes! I'm going to merge it!

Regards,
Christian.

**Pull request merged**
